# Generated by Django 6.0.7 on 2026-08-25 13:55

from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    # Use the profile field value string directly to avoid relying on model constants
    Bookmark.objects.filter(owner__profile__web_archive_integration="enabled").update(
        web_archive=True
    )


def reverse(apps, schema_editor):
    UserProfile = apps.get_model("bookmarks", "UserProfile")
    # Revert opt_in mode back to enabled (the previous "archive everything" mode)
    UserProfile.objects.filter(web_archive_integration="opt_in").update(
        web_archive_integration="enabled"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="web_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards, reverse),
        migrations.AlterField(
            model_name="userprofile",
            name="web_archive_integration",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("opt_in", "Opt-in"),
                    ("enabled", "Enabled"),
                ],
                default="disabled",
                max_length=10,
            ),
        ),
    ]
